from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.core.config import settings
from app.infrastructure.ml.serializer import ModelSerializer
from scripts.build_features import build_features_from_chunks, load_event_chunks
from sklearn.model_selection import train_test_split


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare ML predictions with deterministic rollout.",
    )
    parser.add_argument(
        "--database-url",
        default=settings.database_url,
        help="SQLAlchemy database URL. Default: " + settings.database_url,
    )
    parser.add_argument(
        "--artifact-path",
        default=f"{settings.models_dir}/v1.joblib",
        help="Path to model artifact generated by training.",
    )
    parser.add_argument(
        "--rollout-percentage",
        type=int,
        default=10,
        help="Rollout percentage baseline (0-100).",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=200000,
        help="Number of events processed per chunk while building features.",
    )
    parser.add_argument(
        "--ml-threshold-mode",
        choices=["match_rollout", "fixed"],
        default="match_rollout",
        help="How to convert ML scores into predictions.",
    )
    parser.add_argument(
        "--fixed-threshold",
        type=float,
        default=0.5,
        help="Fixed threshold used when --ml-threshold-mode=fixed.",
    )
    return parser.parse_args()


def stable_rollout(user_id: str, percentage: int = 10) -> bool:
    raw = f"{user_id}:baseline_rollout".encode()
    digest = hashlib.sha256(raw).hexdigest()
    bucket = int(digest[:8], 16) % 100
    return bucket < percentage


def main() -> None:
    args = parse_args()
    if not (0 <= args.rollout_percentage <= 100):
        raise ValueError("--rollout-percentage must be between 0 and 100.")
    if not (0.0 <= args.fixed_threshold <= 1.0):
        raise ValueError("--fixed-threshold must be between 0.0 and 1.0.")

    print("Loading events...")
    event_chunks = load_event_chunks(args.database_url, chunk_size=args.chunk_size)
    print("Building features incrementally...")
    dataset = build_features_from_chunks(event_chunks)
    if dataset.empty:
        raise ValueError("Feature builder returned no rows.")

    print("Loading model...")
    serializer = ModelSerializer()
    artifact = serializer.load(args.artifact_path)

    model = artifact["model"]
    feature_cols = artifact["feature_columns"] or [
        "unique_features",
        "active_days",
        "avg_hour",
        "avg_day_of_week",
        "hours_since_last_event",
        "events_per_day",
    ]
    missing_feature_cols = [col for col in feature_cols if col not in dataset.columns]
    if missing_feature_cols:
        raise ValueError(f"Dataset is missing required model columns: {missing_feature_cols}")

    X = dataset[feature_cols]
    y = dataset["target"]
    if y.nunique() < 2:
        raise ValueError("Need at least two classes to evaluate model quality.")
    if (y.value_counts() < 2).any():
        raise ValueError("Need at least two samples per class for holdout evaluation.")

    test_size = max(0.2, 2 / len(dataset))
    if test_size >= 1:
        test_size = 0.5

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=test_size,
        random_state=42,
        stratify=y,
    )
    eval_df = dataset.loc[X_test.index].copy()

    print("Running predictions...")
    eval_df["ml_score"] = model.predict_proba(X_test)[:, 1]
    target_coverage = args.rollout_percentage / 100.0
    if args.ml_threshold_mode == "match_rollout":
        if target_coverage <= 0:
            ml_threshold = 1.0
        elif target_coverage >= 1:
            ml_threshold = 0.0
        else:
            ml_threshold = float(eval_df["ml_score"].quantile(1 - target_coverage))
    else:
        ml_threshold = args.fixed_threshold

    eval_df["ml_pred"] = (eval_df["ml_score"] >= ml_threshold).astype(int)

    print("Simulating deterministic rollout baseline...")
    eval_df["rollout_pred"] = eval_df["user_id"].astype(str).apply(
        lambda user_id: stable_rollout(user_id, args.rollout_percentage)
    )

    print("\n=== RESULTS ===")

    def evaluate(name, preds):
        accuracy = (preds == y_test).mean()
        positive_rate = preds.mean()

        print(f"\n{name}")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Positive rate: {positive_rate:.4f}")

    evaluate("ML", eval_df["ml_pred"])
    evaluate("Rollout", eval_df["rollout_pred"])

    print("\n=== BUSINESS METRICS ===")

    def engagement_rate(mask):
        selected = eval_df.loc[mask, "target"]
        if selected.empty:
            return 0.0
        return float(selected.mean())

    ml_engagement = engagement_rate(eval_df["ml_pred"] == 1)
    rollout_engagement = engagement_rate(eval_df["rollout_pred"] == 1)

    print(f"ML Engagement: {ml_engagement:.4f}")
    print(f"Rollout Engagement: {rollout_engagement:.4f}")

    uplift = ml_engagement - rollout_engagement
    print(f"Uplift: {uplift:.4f}")
    print(f"ML threshold mode: {args.ml_threshold_mode}")
    print(f"ML threshold: {ml_threshold:.4f}")
    print(f"ML coverage: {eval_df['ml_pred'].mean():.4f}")
    print(f"Rollout coverage: {eval_df['rollout_pred'].mean():.4f}")
    print(f"Artifact path: {args.artifact_path}")
    print(f"Holdout users: {len(eval_df)}")


if __name__ == "__main__":
    main()